apiVersion: v1
kind: ServiceAccount
metadata:
  name: xxl-job
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xxl-job
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xxl-job
subjects:
- kind: ServiceAccount
  name: xxl-job
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: xxl-job
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]