apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: xxl-job
        release: default
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: xxl-job
      serviceAccount: xxl-job
      securityContext: {}
      schedulerName: default-scheduler
      containers:
      - name: xxl-job
        image: zhxl1989/xxl-job:2.3.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 6666
          name: transport
        - containerPort: 9999
          name: executor
        resources:
            limits:
              cpu: '1'
              memory: 2Gi
              #nvidia.com/gpu: 4k
            requests:
              cpu: 500m
              memory: 1Gi
              #nvidia.com/gpu: 4k
        env:
        - name: server.port
          value: "8080"        
        - name: server.servlet.context-path
          value: "/xxl-job-admin"
        - name: datasource.url
          value: "jdbc:mysql://mysql.shenyu.svc.cluster.local:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
        - name: datasource.username
          value: "root"
        - name: datasource.password
          value: "123456"
        - name: datasource.driver.class.name
          value: "com.mysql.cj.jdbc.Driver"
        - name: mail.host
          value: "smtp.qq.com"
        - name: mail.port
          value: "25"
        - name: mail.username
          value: "1024122298@qq.com"
        - name: mail.password
          value: "thomsesrprxebbji"
        - name: mail.properties.mail.smtp.auth
          value: "true"
        - name: mail.properties.mail.smtp.starttls.enable
          value: "true"
        - name: mail.properties.mail.smtp.starttls.required
          value: "true"
        - name: mail.properties.mail.smtp.socketFactory.class
          value: "javax.net.ssl.SSLSocketFactory"
        - name: i18n
          value: "zh_CN"
        - name: fast
          value: "200"
        - name: slow
          value: "100"
        - name: logretentiondays
          value: "30"      
        - name: real_host
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /etc/localtime
          name: volume-localtime
        - name: config
          mountPath: /app/config/application.properties
          #对应面下面的path，保持一致
          subPath: application.properties
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
        - name: config
          configMap:
            #对应config-map的名称
            name: xxl-job-config
            items:
            - key: application.properties
              #对应上面的subPath，保持一致
              path: application.properties