apiVersion: v1
kind: Service
metadata:
  name: xxl-job-executor-sample-springboot
  namespace: default
  labels:
    service: xxl-job-executor-sample-springboot
spec:
  ports:
    - name: executor
      port: 9999
      protocol: TCP
      targetPort: 9999
      nodePort: 30999
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30881
  selector:
    app: xxl-job-executor-sample-springboot
  type: NodePort