apiVersion: v1
kind: Service
metadata:
  name: xxl-job
  namespace: default
  labels:
    service: xxl-job
spec:
  sessionAffinity: "ClientIP"
  ports:
    - name: transport
      port: 6666
      protocol: TCP
      targetPort: 6666
      nodePort: 30666
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30888
    - name: executor
      port: 9999
      protocol: TCP
      targetPort: 9999
      nodePort: 31999
  selector:
    app: xxl-job
  type: NodePort