kind: Service
apiVersion: v1
metadata:
  name: mysql-endpoints
  namespace: shenyu
spec:
  ports:
  - port: 3306
    name: mysql-endpoints
    targetPort: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-endpoints
  namespace: shenyu
subsets:
- addresses:
  - ip: 10.10.10.88
  ports:
  - port: 3306
    name: mysql-endpoints