apiVersion: v1
kind: Service
metadata:
  namespace: shenyu
  name: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shenyu
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: shenyu-pvc
      - name: mysql-config-volume
        configMap:
          name: shenyu-cm
          items:
           - key: my.cnf
             path: my.cnf
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        ports:
        - containerPort: 3306
          protocol: TCP
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123456'
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-config-volume
          mountPath: /etc/mysql/mysql.conf.d