apiVersion: v1
kind: Service
metadata:
  namespace: shenyu
  name: shenyu-demo-svc
spec:
  selector:
    app: shenyu-demo
  type: NodePort
  ports:
  - protocol: TCP
    port: 12306
    targetPort: 12306
    nodePort: 32190
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shenyu
  name: shenyu-demo
spec:
  selector:
    matchLabels:
      app: shenyu-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: shenyu-demo
    spec:
      #volumes:
      #- name: shenyu-demo-config
        #configMap:
          #name: shenyu-cm
          #items:
          #- key: application-demo.yml
           # path: application-demo.yml
      containers:
      - name: shenyu-demo
        image: zhxl1989/boot-demo:12306
        ports:
        - containerPort: 12306
        env:
        - name: TZ
          value: Asia/Beijing
        #volumeMounts:
        #- name: shenyu-demo-config
          #mountPath: /opt/shenyu-demo/conf/application-demo.yml
          #subPath: application-demo.yml