apiVersion: v1
kind: Service
metadata:
  namespace: shenyu
  name: shenyu-demo-svc
spec:
  selector:
    app: shenyu-demo
  type: NodePort
  ports:
  - protocol: TCP
    port: 12306
    targetPort: 12306
    nodePort: 32190
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shenyu
  name: shenyu-demo
spec:
  selector:
    matchLabels:
      app: shenyu-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: shenyu-demo
    spec:
      containers:
      - name: shenyu-demo
        image: zhxl1989/boot-demo:12306
        ports:
        - containerPort: 12306
        resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
        volumeMounts:
        - mountPath: /etc/localtime
          name: volume-localtime
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime  