server:
  servlet:
    context-path: /boot-demo
  port: 12306
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: boot-demo
  security:
    user:
      name: admin
      password: 123456
  sql:
    init:
      schema-locations:
        - classpath*:sql/demo.sql
      continue-on-error: false
      username: root
      password: 123456
      separator: ;
      encoding: UTF-8
      mode: always
      platform: all
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    database-id: mysql